### ISSUE TITLE
Bad seeking of AVC YUV444p10 input

### ISSUE THREAD

**Issue by HuangRuixiao-eng** [AkarinVS/L-SMASH-Works#10]
When I read YUV444 AVC clips in [https://dmhy.anoneko.com/topics/view/365175_Nagi_no_Asukara_2013_BD_Vol_1-9_Fin_1080p_AVC-yuv444p10_FLAC_MKV_mawen1250.html](url) with `core.lsmas.LWLibavSource`, it presented a wrong result after seeking and no waring or error report.

core.lsmas.Version() info:
`{'config': b'-Dcachedir=""""', 'ffmpeg_version': [b'n4.4-dev-3785-g0f6745060e', b'Lavc58.134.100', b'Lavf58.76.100', b'Lavu56.70.100', b'SwS5.9.100'], 'version': b'vA.3e-0-g59ef222'}`

The result is attached below:
![图片](https://user-images.githubusercontent.com/55101368/132940039-3e3136c3-fb48-42f1-9a45-6df77962e626.png)

**Comment by AkarinVS** [comment]
mediainfo:

General
Unique ID                                :
204215944568315336607301036650169645870 (0x99A28F6E489A3995AC98FC64F8D83B2E)
Complete name                            : Nagi no Asukara 2013 - EP01 [BD
1920x1080 23.976fps AVC-yuv444p10 FLACx3 Chap] - mawen1250.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 1.14 GiB
Duration                                 : 23 min 42 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 6 860 kb/s
Encoded date                             : UTC 2014-04-04 04:54:04
Writing application                      : mkvmerge v6.8.0 ('Theme for
Great Cities') 64bit built on Mar  2 2014 21:34:26
Writing library                          : libebml v1.3.0 + libmatroska
v1.4.1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High 4:4:4 ***@***.***
Format settings                          : CABAC / 8 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 8 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 23 min 42 s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:4:4
Bit depth                                : 10 bits
Scan type                                : Progressive
Writing library                          : x264 core 142 r2409+42 f4055d5
7mod ***@***.*** X86_64]
Encoding settings                        : cabac=1 / ref=8 / deblock=1:0:0
/ analyse=0x3:0x133 / me=tesa / subme=10 / psy=1 / fade_compensate=0.00 /
psy_rd=0.60:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 /
8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=4 /
threads=8 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=0 /
interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=12 /
b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 /
weightp=2 / keyint=720 / keyint_min=1 / scenecut=40 / intra_refresh=0 /
rc=crf / mbtree=0 / crf=17.0000 / qcomp=0.70 / qpmin=0:0:0 / qpmax=81:81:81
/ qpstep=4 / ip_ratio=1.40 / pb_ratio=1.30 / aq=3:0.80 /
aq-sensitivity=10.00 / aq-factor=1.00:1.00:1.00 / aq2=0 / aq3=0
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 2
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 23 min 42 s
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Title                                    : Main
Writing library                          : libFLAC 1.3.0 (UTC 2013-05-26)
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 23 min 42 s
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Title                                    : Audio Commentary 1
Writing library                          : libFLAC 1.3.0 (UTC 2013-05-26)
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Audio #3
ID                                       : 4
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 23 min 42 s
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Title                                    : Audio Commentary 2
Writing library                          : libFLAC 1.3.0 (UTC 2013-05-26)
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:Avant
00:03:48.019                             : en:Opening
00:05:17.984                             : en:A Part
00:12:44.055                             : en:B Part
00:21:58.817                             : en:Ending
00:23:31.035                             : en:Preview

**Comment by AkarinVS** [comment]
mediainfo:
```
General
Unique ID                                : 204215944568315336607301036650169645870 (0x99A28F6E489A3995AC98FC64F8D83B2E)
Complete name                            : Nagi no Asukara 2013 - EP01 [BD 1920x1080 23.976fps AVC-yuv444p10 FLACx3 Chap] - mawen1250.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 1.14 GiB
Duration                                 : 23 min 42 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 6 860 kb/s
Encoded date                             : UTC 2014-04-04 04:54:04
Writing application                      : mkvmerge v6.8.0 ('Theme for Great Cities') 64bit built on Mar  2 2014 21:34:26
Writing library                          : libebml v1.3.0 + libmatroska v1.4.1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High 4:4:4 Predictive@L5
Format settings                          : CABAC / 8 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 8 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 23 min 42 s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:4:4
Bit depth                                : 10 bits
Scan type                                : Progressive
Writing library                          : x264 core 142 r2409+42 f4055d5 7mod [10-bit@all X86_64]
Encoding settings                        : cabac=1 / ref=8 / deblock=1:0:0 / analyse=0x3:0x133 / me=tesa / subme=10 / psy=1 / fade_compensate=0.00 / psy_rd=0.60:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=4 / threads=8 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=12 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=720 / keyint_min=1 / scenecut=40 / intra_refresh=0 / rc=crf / mbtree=0 / crf=17.0000 / qcomp=0.70 / qpmin=0:0:0 / qpmax=81:81:81 / qpstep=4 / ip_ratio=1.40 / pb_ratio=1.30 / aq=3:0.80 / aq-sensitivity=10.00 / aq-factor=1.00:1.00:1.00 / aq2=0 / aq3=0
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 2
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 23 min 42 s
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Title                                    : Main
Writing library                          : libFLAC 1.3.0 (UTC 2013-05-26)
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 23 min 42 s
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Title                                    : Audio Commentary 1
Writing library                          : libFLAC 1.3.0 (UTC 2013-05-26)
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Audio #3
ID                                       : 4
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 23 min 42 s
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Title                                    : Audio Commentary 2
Writing library                          : libFLAC 1.3.0 (UTC 2013-05-26)
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:Avant
00:03:48.019                             : en:Opening
00:05:17.984                             : en:A Part
00:12:44.055                             : en:B Part
00:21:58.817                             : en:Ending
00:23:31.035                             : en:Preview
```
