### ISSUE TITLE
alpha clip _Range?

### ISSUE THREAD

**Issue by AkarinVS** [AkarinVS/L-SMASH-Works#11]
should alpha clip defaults to full range?

currently lsmas uses the main clip's range to set the alpha clip's range, primaries, transfer, and matrix.
https://github.com/AkarinVS/L-SMASH-Works/blob/8ba7892ed08095304f61c089b530272388486f77/VapourSynth/video_output.c#L1066-L1075

For alpha clip, primaries and matrix are irrelevant, but I'm not sure about range and transfer.

I'd guess all alpha should be full range, but is this true?
What about transfer?

Also, is there a YUV image/video format that also includes alpha channel?

**Comment by YomikoR** [comment]
They are just masks, and _Range is the only required property.
