### ISSUE TITLE
Support for unicode filepaths

### ISSUE THREAD

**Issue by Ryuukishi** [AkarinVS/L-SMASH-Works#13]
Trying to open a file with Japanese characters in its filepath returns ```vapoursynth.Error: lsmas: failed to open file.``` 
Unicode filenames should be supported by VS and ffms2 opens it fine without any problems.

**Comment by AkarinVS** [comment]
Are you using utf-8 to encode your vpy script?
lsmas should handle utf-8 paths just fine (but not local multibyte
encodings)

**Comment by Ryuukishi** [comment]
Yeah, I have no idea why it isn't working. I tested it on another machine and it ran fine. Sorry for the trouble.
