### ISSUE TITLE
Seeking is slowww since release vA.3g

### ISSUE THREAD

**Issue by YomikoR** [AkarinVS/L-SMASH-Works#24]
When I was dealing with a certain m2ts source file (to be specific, 2/00007 of Kimagure Orange Road by Discotek), although the sequential playback was very smooth, seeking turned out to be quite slow. I tried other versions from the release list and ended up with vA.3f working as expected.

**Comment by AkarinVS** [comment]
Thanks for the report. I will take a look, but it will probably take some time.

**Comment by AkarinVS** [comment]
sorry for the delay. please see if https://github.com/AkarinVS/L-SMASH-Works/releases/tag/vA.3i helps.

You will need to remove existing `*.lwi` files and make lsmas reindex the input.

**Comment by YomikoR** [comment]
Thanks so much. It works like a charm.
