### ISSUE TITLE
const variable reassignment

### ISSUE THREAD

**Issue by Asd-g** [AkarinVS/L-SMASH-Works#25]
In `decode.c` there are two reassignments of const var:
- https://github.com/AkarinVS/L-SMASH-Works/blob/ffmpeg-4.5/common/decode.c#L74
- https://github.com/AkarinVS/L-SMASH-Works/blob/ffmpeg-4.5/common/decode.c#L100

**Comment by AkarinVS** [comment]
`const AVCodec *codec` means a pointer to const AVCodec object`, so we
can't modify the object the pointer points to, but we can modify the
pointer itself.
contrast that with `AVCodec *const codec = NULL;`, which means the pointer
variable itself is constant but we can modify the object the pointer points
to.

Or am I missing something?

**Comment by Asd-g** [comment]
You're right. I got confused them.
