### ISSUE TITLE
prefer_hw=3 failing

### ISSUE THREAD

**Issue by couleurm** [AkarinVS/L-SMASH-Works#28]
I'm on a Windows Sandbox machine which probably has some Microsoft Basic Display Adapter or something around those lines, so it definitely fails at loading the NVCUVID DLL but the issue is that it doesn't try quicksync and software in that order like said in documentation, anything I did wrong?

![image](https://user-images.githubusercontent.com/82747632/207029435-eda5e30e-a4bb-425a-9507-783343cab287.png)

**Comment by couleurm** [comment]
![image](https://user-images.githubusercontent.com/82747632/207030972-7b7b13ce-4554-40b8-a610-7ffe31b43dd4.png)
same with python 3.10
using your vapoursynth-classic that has sort fix

**Comment by AkarinVS** [comment]
ffmpeg had a bug that it will crash the entire process when cuvid is requested but not available, so lsmas never lived to try qsv.

https://github.com/FFmpeg/FFmpeg/commit/07bcedc232feeb9e30336624f4e9977d47ac43bc

will upload a new build soon.

**Comment by AkarinVS** [comment]
Please try https://github.com/AkarinVS/L-SMASH-Works/releases/tag/vA.3k.

**Comment by couleurm** [comment]
Worked, thank you 🙏🙏
